#ifndef EVENT_MANIFEST_H
#define EVENT_MANIFEST_H

// Engine-wide event type identifiers
typedef enum {
    EVENT_ZERO = 0, // Reserved
    ON_LOAD,
    ON_EXIT,
    ON_BUTTON_UP_PRESSED,
    ON_BUTTON_UP_HELD,
    ON_BUTTON_DOWN_PRESSED,
    ON_BUTTON_DOWN_HELD,
    ON_BUTTON_LEFT_PRESSED,
    ON_BUTTON_LEFT_HELD,
    ON_BUTTON_RIGHT_PRESSED,
    ON_BUTTON_RIGHT_HELD,
    ON_BUTTON_A_PRESSED,
    ON_BUTTON_A_HELD,
    ON_BUTTON_B_PRESSED,
    ON_BUTTON_B_HELD,
    ON_BUTTON_START_PRESSED,
    ON_BUTTON_START_HELD,
    ON_BUTTON_SELECT_PRESSED,
    ON_BUTTON_SELECT_HELD,
    ON_COLLISION,
    ON_CREATE_ENTITY,
    ON_DESTROY_ENTITY
} EventType;

#define GLOBAL_EVENT 254

#endif